apiVersion: v1
kind: ConfigMap
metadata:
  name: laurus-global-config
  namespace: laurus-apps
data:
  PORT: "5000"
  REACT_APP_API_URL: "http://laurus-backend-service:80"
---
apiVersion: v1
kind: Secret
metadata:
  name: laurus-db-secret
  namespace: laurus-apps
type: Opaque
stringData:
  # Connects directly to the ClusterIP Service defined in mongodb.yml
  MONGODB_URI: "mongodb://admin:password123@mongodb-service:27017/laurus?authSource=admin"